config/routes.rb
SampleApp::Application.routes.draw do
  resources :vote_posts

  resources :posts   do
    resources :replies
    resources :vote_posts
  end

  resources :users do
    member do
      post :addadmin , :removeadmin
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/replies/edit' , :to => 'replies#edit'
  match '/vote_posts/edit' , :to => 'vote_posts#edit'
    root              :to => 'posts#index'

=begin
  get "pages/home"

  get "pages/contact"

  get "pages/help"

  get "pages/about"
=end

end

app/models/vote_post.rb
class VotePost < ActiveRecord::Base
  belongs_to :post, :counter_cache => true
  belongs_to :user
  attr_accessible :user_id, :post_id, :count

  after_initialize :init

  def init
      self.count = 0 if self.count.nil?
  end
end

app/controllers/vote_posts_controller.rb
class VotePostsController < ApplicationController
  # GET /vote_posts
  # GET /vote_posts.xml
  def index
    @vote_posts = VotePost.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @vote_posts }
    end
  end

  # GET /vote_posts/1
  # GET /vote_posts/1.xml
  def show
    @vote_post = VotePost.find(params[:id])

   # respond_to do |format|
    #  format.html # show.html.erb
     # format.xml  { render :xml => @vote_post }

  end

  # GET /vote_posts/new
  # GET /vote_posts/new.xml
  def new
    @vote_post = VotePost.new
     respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vote_post }
    end
  end

  # GET /vote_posts/1/edit
  def edit
    @vote_post = VotePost.find(params[:post_id])
    if (current_user.id == @vote_post.user_id)
    else

    @vote_post.count = @vote_post.count + 1
    @vote_post.update_attributes(params[:count])
    end
    redirect_to posts_path
  end

  # POST /vote_posts
  # POST /vote_posts.xml
  def create
    @vote_post = current_user.vote_post.build(params[:id])
    @vote_post.count = @vote_post.count+1
    @vote_post.update_attributes(params[:count])
    @vote_post.save

    #respond_to do |format|

      #if @vote_post.save
        #format.html { #redirect_to(@vote_post, :notice => 'Vote post was successfully created.') }
       # format.xml  { #render :xml => @vote_post, :status => :created, :location => @vote_post }
      #else
     #   format.html { #render :action => "new" }
      #  format.xml  { #render :xml => @vote_post.errors, :status => :unprocessable_entity }
     # end
  end




  # PUT /vote_posts/1
  # PUT /vote_posts/1.xml
  def update
    @vote_post = VotePost.find(params[:id])

    respond_to do |format|
      if @vote_post.update_attributes(params[:vote_post])
        format.html { redirect_to(@vote_post, :notice => 'Vote post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vote_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vote_posts/1
  # DELETE /vote_posts/1.xml
  def destroy
    @vote_post = VotePost.find(params[:id])
    @vote_post.destroy

    respond_to do |format|
      format.html { redirect_to(vote_posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/vote_posts_helper.rb
module VotePostsHelper
end

app/views/vote_posts/_form.html.erb
<%= form_for(@vote_post) do |f| %>
  <% if @vote_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote_post.errors.count, "error") %> prohibited this vote_post from being saved:</h2>

      <ul>
      <% @vote_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vote_posts/edit.html.erb
<h1>Editing vote_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote_post %> |
<%= link_to 'Back', vote_posts_path %>

app/views/vote_posts/index.html.erb
<h1>Are you sure?</h1>

<table>
  <tr>
    <th>Count</th>
    <th>Post id</th>
    <th>User id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= form_for([@post, @post.vote_post.build]) do |f| %>
  <div class="field">
    <%= f.hidden_field :count%><br />
  </div>
   <div class="field">
    <%= f.hidden_field :post_id %><br />
  </div>
  <div>
  <%= f.submit%>
  </div>
 <% end %>

<% @vote_posts.each do |vote_post| %>
  <tr>
    <td><%= vote_post.count %></td>
    <td><%= vote_post.post_id %></td>
    <td><%= vote_post.user_id %></td>
    <td><%= link_to 'Show', vote_post %></td>
    <td><%= link_to 'Edit', edit_vote_post_path(vote_post) %></td>
    <td><%= link_to 'Destroy', vote_post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote post', new_vote_post_path %>

app/views/vote_posts/new.html.erb
<h1>New vote_post</h1>

<%= render 'form' %>

<%= link_to 'Back', vote_posts_path %>

app/views/vote_posts/show.html.erb
<p id="notice"><%= notice %></p>


<%= form_for([@post, @post.vote_posts.build]) do |f| %>
  <div class="field">
    <%= f.hidden_field :count%><br />
  </div>
   <div class="field">
    <%= f.hidden_field :post_id %><br />
  </div>
  <div>
  <%= f.submit%>
  </div>
 <% end %>




<%=# link_to 'Edit', edit_vote_post_path(@vote_post) %> |
<%= #link_to 'Back', vote_posts_path %>