config/routes.rb
SampleApp::Application.routes.draw do
  resources :vote_posts

  resources :posts   do
    resources :replies
    resources :vote_posts
  end

  resources :users do
    member do
      post :addadmin , :removeadmin
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/replies/edit' , :to => 'replies#edit'
  match '/vote_posts/edit' , :to => 'vote_posts#edit'
    root              :to => 'posts#index'

=begin
  get "pages/home"

  get "pages/contact"

  get "pages/help"

  get "pages/about"
=end

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  has_many :posts,  :dependent => :destroy
  has_many :replies, :dependent => :destroy
  has_many :vote_posts
  has_many :votereplies
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
 
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  before_save :encrypt_password
  
  def has_password?(submitted_password)
  encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def self.search(search)
    if search
     find(:all, :conditions => ['name LIKE ?',"%#{search}%"])
    else
     find(:all)
    end
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => [:destroy, :addadmin, :removeadmin]
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
    sign_in @user
    redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @title = "Edit user"
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def index
      @title = "All users"
    # @users = User.paginate(:page => params[:page])
      @users = User.search(params[:search])
  end


 # def show
 #   @user = User.find(params[:id])
 #   @title = @user.name
 # end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  def search
    @user = User.search(params[:search])
  end

  def addadmin
    @user = User.find(params[:id])
    @user.toggle!(:admin)
    @user.update_attributes(params[:user])
    @user.save
    flash[:notice] = "Successfully Given Admin Privileges"

    redirect_to users_path
  end


  def removeadmin
    @user = User.find(params[:id])
    @user.toggle!(:admin)
    @user.update_attributes(params[:user])
    @user.save
    flash[:notice] = "Successfully Revoked Admin Privileges"

    redirect_to users_path
  end



    private

    def authenticate
      deny_access unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_search.html.erb
<% form_tag   do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
    <%= link_to_function "Clear", "$('search_field').clear()" %>
<% end %>

app/views/users/_search_results.html.erb
<ul>
   <% @users.each do |user| %>
       <li> <%= link_to user.name, user %> </li>
   <% end %>
 </ul>


app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>


app/views/users/index.html.erb
<h1>All users</h1>

<table>
  <tr>
    <th>Name</th>

   </tr>
<%#= will_paginate(@users)%>

  <% @users.each do |user| %>
    <tr>
       <td><%= link_to user.name, user %></td>
      <% if signed_in? %>
         <% if current_user.admin? %>  

           <%if user.admin == true %>
            <td></td>
            <%else%>  
               <td><%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{user.name}" %> <% end %>      </td>
          
            <% if current_user.id == user.id && user.admin == true %> 
             <td></td>
            <%elsif user.admin == true %> 
	 <td><%=link_to 'Remove Admin Status', "/users/#{user.id}/removeadmin/", :method=>:post, :confirm => "You sure?", %>
  <%else%>   </td>
        <td> <%=link_to 'Grant Admin Status', "/users/#{user.id}/addadmin/", :method=>:post, :confirm => "You sure?", %>
  <%end%>  </td>

        </tr>
  <% end %>
  <% end %>
      <% end %>

<%#=will_paginate(@users)%>
 </table>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
 <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Password Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
 Welcome <%= @user.name %>. You are now Signed in!
  <tr>
    <td class="main">
     </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %> <br />
      <strong>Total Posts posted</strong> <%= @user.posts.count %>
      <strong>Total Replies given</strong> <%= @user.replies.count %>
    </td>

        <li><%= link_to "Create a Post", new_post_path%></li>
        <li><%= link_to "View Posts", posts_path %></li>
   </tr>
</table>