config/routes.rb
SampleApp::Application.routes.draw do
  resources :vote_posts

  resources :posts   do
    resources :replies
    resources :vote_posts
  end

  resources :users do
    member do
      post :addadmin , :removeadmin
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/replies/edit' , :to => 'replies#edit'
  match '/vote_posts/edit' , :to => 'vote_posts#edit'
    root              :to => 'posts#index'

=begin
  get "pages/home"

  get "pages/contact"

  get "pages/help"

  get "pages/about"
=end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :replies
  has_many :vote_posts
  attr_accessible :content, :title, :user_id, :count, :most_active
  default_scope :order => 'posts.most_active DESC'
  validates :title, :presence => true
  validates :content, :presence => true
  validates_uniqueness_of :user_id, :scope => "id"

    def self.search(search)
    if search
     find(:all, :conditions => ['content LIKE ?',"%#{search}%"])
    else
     find(:all)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.search(params[:search])
    #@posts = Post.all

    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.xml  { render :xml => @posts }
    #end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end


  def VotePost.create
      @vote_post = current_user.vote_post.build(params[:id])
       respond_to do |format|

      if @vote_post.save
        format.html { redirect_to(@vote_post, :notice => 'Vote post was successfully created.') }
        format.xml  { render :xml => @vote_post, :status => :created, :location => @vote_post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @vote_post.errors, :status => :unprocessable_entity }
      end
    end
   end



  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])

    if (current_user.id == @post.user_id)
      flash[:error] = "You cannot vote your own post"
    else
      @post.count = @post.count + 1
    
  if @post.most_active.nil?
        @post.most_active = (0.8 * @post.count) + (0.0000002 * ((@post.updated_at).to_time.to_f))
      else
       @post.most_active = (0.8 * @post.count) + (0.2 * @post.most_active)
    end
      @post.update_attributes(params[:count])
    end
#    redirect_to :controller => VotePost, :action => show, :id => @post
    redirect_to posts_path
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post  = current_user.posts.build(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <td class="post">
    <span class="content"><%= post.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(post.created_at) %> ago.
    </span>
  </td>
</tr>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
<h1>Vote updated successfully</h1>

<%= form_for([@post, @post.replies.build]) do |f| %>
  <div class="field">
    <%= f.hidden_field :repcount%><br />
  </div>
   <div class="field">
    <%= f.hidden_field :post_id %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= render 'form' %>


<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Top Questions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Votes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= post.count %></td>
    <td><%= link_to 'View Replies', post %></td>
     <% if signed_in? %>
    <td><%= link_to 'Vote', edit_post_path(post) %></td>
        <% if current_user.admin? %>
     <td><%= link_to "delete", post, :method => :delete, :confirm => "Are You sure?", :title => "Delete #{post.title}" %> </td>
  </tr>
        <% end %>
        <% end %>

  <% end %>
</table>
 
<%if !signed_in? %>

<%= link_to "Sign in now!", signin_path, :class => "signup_button round" %>
<br> &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Don't have an account? <%= link_to "Sign up", signup_path %>

<br />
<% end %>
<% if signed_in? %>
 <%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>



 <h1> Replies </h1>

<table>
  <tr>
    <th>Response</th>
    <th>Vote</th>
  </tr>

<%= form_for([@post, @post.replies.build]) do |f| %>
    <% @post.replies.each do |reply| %>
     <tr>
    <td><%= reply[:response] %></td>
    <td><%= reply[:repcount] %></td>
       <% if signed_in? %>
    <td><%= link_to 'Vote Reply', :controller => 'replies', :action => 'edit', :id => reply[:id]%> </td>
           <% end %>
   </tr>
               <div class="field">
    <%= f.hidden_field :id %><br />
  </div>
           <% end %>
        <% end %>
    </table>
<% if signed_in? %>
<h1>Add a reply:</h1>
  <%= form_for([@post, @post.replies.build]) do |f| %>
   <div class="field">
    <%= f.label :response %><br />
    <%= f.text_area :response %>
  </div>
   <div class="field">
    <%= f.hidden_field :post_id %><br />
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |

<% end %>
<%= link_to 'Back', posts_path %> <br>
<% if !(signed_in?) %>
   You are not logged in! Only logged in users can comment on the post.
   <%= link_to 'Sign In', signin_path %> here
<% end %>