config/routes.rb
SampleApp::Application.routes.draw do
  resources :vote_posts

  resources :posts   do
    resources :replies
    resources :vote_posts
  end

  resources :users do
    member do
      post :addadmin , :removeadmin
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/replies/edit' , :to => 'replies#edit'
  match '/vote_posts/edit' , :to => 'vote_posts#edit'
    root              :to => 'posts#index'

=begin
  get "pages/home"

  get "pages/contact"

  get "pages/help"

  get "pages/about"
=end

end

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Posts", posts_path %></li>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <li><%= link_to "Users", users_path %></li>
      <% end %>
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>

      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>

      <section class="round">
                <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>

<% form_tag users_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Users", :name => nil %>
  </p>
<% end %>


<% form_tag posts_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Posts", :name => nil %>
  </p>
<% end %>
        
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>


</html>